FROM debian:bookworm-20240211

WORKDIR /app

RUN apt-get update \
    && apt-get install -y ca-certificates \
    && apt-get -y install curl \
    && apt-get -y install ffmpeg

EXPOSE 50051

ARG GOOGLE_SA_KEY
ARG YRAL_METADATA_TOKEN
ARG QSTASH_CURRENT_SIGNING_KEY
ARG QSTASH_AUTH_TOKEN
ARG STORJ_ACCESS_KEY_ID
ARG STORJ_SECRET_KEY

ENV GOOGLE_SA_KEY=$GOOGLE_SA_KEY
ENV YRAL_METADATA_TOKEN=$YRAL_METADATA_TOKEN
ENV QSTASH_CURRENT_SIGNING_KEY=$QSTASH_CURRENT_SIGNING_KEY
ENV QSTASH_AUTH_TOKEN=$QSTASH_AUTH_TOKEN
ENV STORJ_ACCESS_KEY_ID=$STORJ_ACCESS_KEY_ID
ENV STORJ_SECRET_KEY=$STORJ_SECRET_KEY


# Latest releases available at https://github.com/aptible/supercronic/releases
# ENV SUPERCRONIC_URL=https://github.com/aptible/supercronic/releases/download/v0.2.29/supercronic-linux-amd64 \
#     SUPERCRONIC=supercronic-linux-amd64 \
#     SUPERCRONIC_SHA1SUM=cd48d45c4b10f3f0bfdd3a57d054cd05ac96812b

# RUN curl -fsSLO "$SUPERCRONIC_URL" \
#     && echo "${SUPERCRONIC_SHA1SUM}  ${SUPERCRONIC}" | sha1sum -c - \
#     && chmod +x "$SUPERCRONIC" \
#     && mv "$SUPERCRONIC" "/usr/local/bin/${SUPERCRONIC}" \
#     && ln -s "/usr/local/bin/${SUPERCRONIC}" /usr/local/bin/supercronic

# # You might need to change this depending on where your crontab is located
# COPY crontab crontab

COPY ./target/x86_64-unknown-linux-musl/release/icp-off-chain-agent .
CMD ["./icp-off-chain-agent"]
