use crate::{
    app_state::AppState,
    events::types::{self, deserialize_event_payload, EventPayload},
};
use anyhow::Result;
use candid::Principal;
use serde_json::Value;
use yral_metadata_types::SendNotificationReq;
use yral_spacetime_bindings::autogenerated::backend::{
    LikedPayload, NotificationType, VideoUploadPayload,
};

const METADATA_SERVER_URL: &str = "https://yral-metadata.fly.dev";

#[derive(Clone)]
pub struct NotificationClient {
    api_key: String,
}

impl NotificationClient {
    pub fn new(api_key: String) -> Self {
        Self { api_key }
    }

    pub async fn send_notification(&self, ref data: SendNotificationReq, user_id: Principal) {
        let client = reqwest::Client::new();
        let url = format!(
            "{}/notifications/{}/send",
            METADATA_SERVER_URL,
            user_id.to_text()
        );

        let res = client
            .post(&url)
            .bearer_auth(&self.api_key)
            .json(&data)
            .send()
            .await;

        if let Err(e) = res {
            log::error!("Error sending notification: {:?}", e);
        }
    }
}

pub async fn dispatch_notif(
    event_type: &str, // todo make this an enum
    params: Value,
    app_state: &AppState,
) -> Result<(), Box<dyn std::error::Error>> {
    let event = deserialize_event_payload(event_type, params)?;

    event.send_notification(app_state).await;

    match event {
        EventPayload::VideoUploadSuccessful(payload) => {
            app_state
                .backend_ctx
                .add_notification(
                    payload.publisher_user_id,
                    NotificationType::VideoUpload(VideoUploadPayload {
                        video_id: payload.post_id,
                    }),
                )
                .await??;
        }
        EventPayload::LikeVideo(payload) => {
            app_state
                .backend_ctx
                .add_notification(
                    payload.publisher_user_id,
                    NotificationType::Liked(LikedPayload {
                        by_user_principal: payload.user_id.to_text(),
                        post_id: payload.post_id,
                    }),
                )
                .await??;
        }
        _ => {}
    }
    Ok(())
}
